
"""
THIS FILE IS GENERATED BY THE RULE PARSER!
DO NOT EDIT THIS FILE!
"""

from ....constants.char_ability import *
from ....constants.stage import *
from ....constants.stage_objs import *
from ....rule_builder.functions_ability_char import *
from ....rule_builder.functions_enemies import *
from ....rule_builder.functions_stage_obj import *
from ....rule_builder.functions_tricks import *
from ....world_base import SonicHeroesWorldBase

from ....constants.loc_region import SonicHeroesRegionData


REGIONS: list[SonicHeroesRegionData] = \
[
    SonicHeroesRegionData(region_name="Seaside Hill Dark Start", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark ObjSanity", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark After Beginning Falling Ruins After Start Of Level", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Beginning Flower Patch After Start Of Level", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Lower Path After Beginning Flower Patch After Start Of Level", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Upper Path After Beginning Flower Patch After Start Of Level", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Loop Before Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Eggmans Robots Bottom Before Checkpoint 1", obj_checks=4),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Hermit Crab Cliff Below Eggmans Robots Before Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Eggmans Robots Middle Before Checkpoint 1", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Eggmans Robots Top Before Checkpoint 1", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Bonus Key 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Small Cliff Above Eggmans Robots Before Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Top Cliff Route With Hermit Crab Before Checkpoint 1", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Bottom Cliff Route Before Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Bottom At Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Bottom At Checkpoint 1 Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Middle After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Middle After Checkpoint 1 Egg Flappers", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Staircase Before Corner Cave Top After Checkpoint 1", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin Before Corner Cave After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Corner Cave After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island After Checkpoint 1", obj_checks=5),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island After Checkpoint 1 Cannon Speed", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island After Checkpoint 1 Cannon Power", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island After Checkpoint 1 Cannon Flying", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island Top Pillar Right After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Island Top Pillar Left After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Ruin Between First and Second Island After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Ruin Between First and Second Island After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Third Ruin Between First and Second Island After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Third Ruin Between First and Second Island After Checkpoint 1 Egg Flappers", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Island After Checkpoint 1", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Island After Checkpoint 1 High Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin After Second Island After Checkpoint 1", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin Stairs After Second Island After Checkpoint 1", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Before First Bobsled After Checkpoint 1", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Bobsled After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Bobsled After Block After Checkpoint 1", obj_checks=7),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Bobsled Small Island After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin After First Bobsled After Checkpoint 1", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin After First Bobsled After Checkpoint 1", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark First Cliff Before Big Ruin Beach At Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Cliff Before Big Ruin Beach After Checkpoint 2", obj_checks=4),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Lower Cliff Before Big Ruin Beach After Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Ruin Beach After Checkpoint 2", obj_checks=8),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Ruin Beach After Checkpoint 2 Cannon Speed", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Ruin Beach After Checkpoint 2 Cannon Power", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Ruin Beach After Checkpoint 2 Cannon Flying", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Lower Cliffs At Start After Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Ruin With Dash Ramp After Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Island 1 After Checkpoint 2", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Bonus Key 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Island 1 After Checkpoint 2 High Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Island 1 After Checkpoint 2 Mid Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin Between Big Ruin Beach Islands After Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Middle Path Top Corner After Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Middle Path Before Blocks After Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Middle Path After Blocks After Checkpoint 2", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Top Path 1 After Checkpoint 2", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Top Path 2 After Checkpoint 2", obj_checks=8),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Island 2 Before Checkpoint 3", obj_checks=5),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach Ruin Staircase Before Checkpoint 3", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach End Path Before Checkpoint 3", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Ruin Beach End Path Before Checkpoint 3 Item Balloon", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Volcano Start At Checkpoint 3", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Checkpoint 3", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Special Ruin Before Volcano After Checkpoint 3", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Ruin After Big Special Ruin Before Volcano After Checkpoint 3", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path After Big Special Ruin Before Volcano Start After Checkpoint 3", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path After Big Special Ruin Before Volcano Loop After Checkpoint 3", obj_checks=3),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Cave Before Volcano Entrance After Checkpoint 3", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Cave Before Volcano After First Block After Checkpoint 3", obj_checks=2),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Cave Before Volcano After Second Block After Checkpoint 3", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room After Checkpoint 3", obj_checks=6),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room Alcove After Checkpoint 3", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Bonus Key 3", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room After Checkpoint 3 Cannon Speed", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room After Checkpoint 3 Cannon Power", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Cannon Room After Checkpoint 3 Cannon Flying", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Volcano Top Room After Checkpoint 3", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Bobsled Start At Checkpoint 4", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Checkpoint 4", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Second Bobsled After Checkpoint 4", obj_checks=6),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Loop After Second Bobsled After Checkpoint 4", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Path Before Big Loop After Checkpoint 4", obj_checks=1),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Big Loop After Checkpoint 4", obj_checks=5),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Whale Blowhole Before Goal", obj_checks=0),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Whale Island Top At Goal", obj_checks=6),
    SonicHeroesRegionData(region_name="Seaside Hill Dark Goal", obj_checks=100)
]